url: http://home.ustc.edu.cn  # Change to "http://staff.ustc.edu.cn" if you're a staff
baseurl: /~liuyuanche               # Change to "/~" plus your email username

theme: minima
title: "Liu Yuanche's page" # Your home page name
description: "new homepage"      # Your description

exclude:
  - '.*'
  - '*.yml'
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - /script
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
